version: "3.3"
services:
  api:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8001:80
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
